

# This file was *autogenerated* from the file /home/sage/project/main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_9 = Integer(9); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_128 = Integer(128); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
import os

# On récupère le dossier où se trouve le script main.sage
os.chdir("/home/sage/project")

load("src/paillier.sage")
load("src/client.sage")
load("src/server.sage")

# ------------------------
# Base de données
# ------------------------

ell = _sage_const_2 
database = [_sage_const_5 , _sage_const_9 ,
            _sage_const_3 , _sage_const_7 ]

client = PIRClient2D(bits=_sage_const_128 )
server = PIRServer2D(database, ell)

# On veut l'élément (1,0) → valeur 3
i_star = _sage_const_1 
j_star = _sage_const_0 

alpha, beta = client.generate_query(i_star, j_star, ell)

encrypted_result = server.answer_query(alpha, beta, client.crypto)

result = client.decrypt_result(encrypted_result)

print("Élément demandé :", database[i_star*ell + j_star])
print("Résultat PIR :", result)

